#!/usr/bin/env bash
set -euo pipefail

# -----------------------------
# Config
# -----------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MODELS_DIR="$IA_DIR/.ollama_models"
LOG_FILE="$IA_DIR/ollama-serve.log"
ENV_FILE="$IA_DIR/env.sh"

MODEL_DEFAULT="qwen2.5:7b-instruct"
MODEL="${OLLAMA_MODEL:-$MODEL_DEFAULT}"
HOST="${OLLAMA_HOST:-127.0.0.1:11434}"

# -----------------------------
# Helpers
# -----------------------------
have_cmd() { command -v "$1" >/dev/null 2>&1; }

log() { echo "[setup-ollama] $*"; }

fail() { echo "[setup-ollama] ERROR: $*" >&2; exit 1; }

wait_api() {
  local url="http://$HOST/api/tags"
  for _ in {1..40}; do
    if curl -fsS "$url" >/dev/null 2>&1; then return 0; fi
    sleep 1
  done
  return 1
}

stop_system_service_if_any() {
  # Evita conflito com serviço systemd usando outro diretório de modelos
  if have_cmd systemctl; then
    if systemctl is-active --quiet ollama 2>/dev/null; then
      log "Stopping systemd ollama service (to avoid conflicts)..."
      sudo systemctl stop ollama || true
    fi
  fi
}

kill_user_ollama_serve() {
  pkill -f "ollama serve" >/dev/null 2>&1 || true
}

flatten_models_dir() {
  # Corrige caso: .ollama_models/.ollama_models/{blobs,manifests}
  if [ -d "$MODELS_DIR/.ollama_models" ]; then
    log "Found nested models dir: $MODELS_DIR/.ollama_models"
    log "Merging nested contents into $MODELS_DIR ..."

    if have_cmd rsync; then
      rsync -a "$MODELS_DIR/.ollama_models/" "$MODELS_DIR/"
    else
      cp -a "$MODELS_DIR/.ollama_models/." "$MODELS_DIR/" 2>/dev/null || true
    fi

    rm -rf "$MODELS_DIR/.ollama_models"
    log "Nested models dir removed."
  fi
}

ensure_deps() {
  if have_cmd apt-get; then
    log "Ensuring dependencies (curl, ca-certificates, zstd)..."
    sudo apt-get update >/dev/null
    sudo apt-get install -y curl ca-certificates zstd >/dev/null
    sudo apt-get install -y rsync >/dev/null || true
  fi
}

install_ollama_if_missing() {
  if have_cmd ollama; then
    log "Ollama already installed: $(ollama -v 2>/dev/null || true)"
    return 0
  fi

  log "Ollama not found. Installing..."
  ensure_deps
  curl -fsSL https://ollama.com/install.sh | sh

  have_cmd ollama || fail "Ollama install finished but 'ollama' not found in PATH."
  log "Ollama installed: $(ollama -v 2>/dev/null || true)"
}

write_env_file() {
  cat > "$ENV_FILE" <<EOF
# Auto-generated by ia/script/setup-ollama.sh
# Usage: source ./env.sh

export OLLAMA_HOST="$HOST"
export OLLAMA_MODELS="$MODELS_DIR"
export OLLAMA_MODEL="$MODEL"

# Optional app vars (use in your backend)
export LLM_BASE_URL="http://$HOST"
export LLM_MODEL="$MODEL"
EOF
  log "Wrote env file: $ENV_FILE"
}

start_server_user_mode() {
  mkdir -p "$MODELS_DIR"
  flatten_models_dir

  log "Starting Ollama server (user-mode) with:"
  log "  OLLAMA_HOST=$HOST"
  log "  OLLAMA_MODELS=$MODELS_DIR"
  log "  log=$LOG_FILE"

  kill_user_ollama_serve

  OLLAMA_HOST="$HOST" OLLAMA_MODELS="$MODELS_DIR" nohup ollama serve >"$LOG_FILE" 2>&1 &

  if ! wait_api; then
    log "Server did not become ready. Showing last lines of log:"
    tail -n 200 "$LOG_FILE" || true
    fail "Ollama server failed to start."
  fi
}

pull_model() {
  log "Pulling model: $MODEL"
  OLLAMA_HOST="$HOST" OLLAMA_MODELS="$MODELS_DIR" ollama pull "$MODEL" >/dev/null
  log "Model pulled."
}

show_status() {
  log "API tags (first bytes):"
  curl -s "http://$HOST/api/tags" | head -c 800
  echo
  log "Local model dir size:"
  du -sh "$MODELS_DIR" 2>/dev/null || true
}

# -----------------------------
# Main
# -----------------------------
log "IA dir:     $IA_DIR"
log "Models dir: $MODELS_DIR"
log "Model:      $MODEL"
log "Host:       $HOST"

install_ollama_if_missing
stop_system_service_if_any
start_server_user_mode
pull_model
write_env_file
show_status

log "Done."
log "Next:"
log "  cd $IA_DIR"
log "  source ./env.sh"
log "  ollama run \$OLLAMA_MODEL \"responda apenas OK\""
